export const queryKeys = {
	fetchAgencies: "fetchAgencies",
	fetchAgencyById: "fetchAgencyId",
	fetchServices: "fetchServices",
	fetchServicesByAgencyId: "fetchServicesByAgencyId",
	fetchServicesByProviderId: "fetchServicesByProviderId",
	fetchServicesProvidersByAgencyId: "fetchServicesProvidersByAgencyId",
	fetchServicesProviders: "fetchServicesProviders",
	fetchServicesPrices: "fetchServicesPrices",
	fetchServicesPricesByAgencyId: "fetchServicesPricesByAgencyId",
	fetchEmployeesByAgencyId: "fetchEmployeesByAgencyId",
	fetchStates: "fetchStates",
	fetchInvoices: "fetchInvoices",
	fetchInvoiceById: "fetchInvoiceById",
	fetchInvoicesByAgencyId: "fetchInvoicesByAgencyId",
	fetchInvoicesByEmployeeId: "fetchInvoicesByEmployeeId",
	fetchInvoicesByCustomerId: "fetchInvoicesByCustomerId",
	fetchInvoicesByRecieverId: "fetchInvoicesByRecieverId",
	fetchInvoicesByStatus: "fetchInvoicesByStatus",
	fetchInvoicesByDate: "fetchInvoicesByDate",
	fetchInvoicesByDateRange: "fetchInvoicesByDateRange",
	fetchInvoicesByDateRangeAndStatus: "fetchInvoicesByDateRangeAndStatus",
	fetchInvoicesByDateRangeAndEmployeeId: "fetchInvoicesByDateRangeAndEmployeeId",
};
